---

- name: Installation des packages
  become: true
  apt:
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    name:
      - sudo
      - vim
      - htop
      - git
      - ca-certificates
      - avahi-daemon
      - byobu
      - python-pip
      - python-dev
      - unzip
      - realpath

- name: MAJ des paquets APT
  become: true
  apt:
    upgrade: yes
    update_cache: yes

...
