---

- name: Installation des packages
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=3600
  become: true
  force_apt_get: true
  with_items:
    - sudo
    - vim
    - htop
    - git
    - ca-certificates
    - avahi-daemon
    - byobu
    - python-pip
    - python-dev
    - unzip
    - realpath

- name: MAJ des paquets APT
  become: true
  force_apt_get: true
  apt:
    upgrade: yes
    update_cache: yes

...